# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jingkai He
email: jaxihe[at]gmail[dot]com
description: |
 Building accounting software at FreeAgent by day.
 Sipping whiskey and hacking odd OSS at Github by night.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jaxi.github.io" # the base hostname & protocol for your site
twitter_username: Jaxihe
github_username:  jaxi

# Build settings
highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
